name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0 
    - name: Setup AppCenter Cli
      run: npm install -g appcenter-cli
    - name: Prepare Package
      run: mvn -DskipTests -P prepare-for-upload package
    - name: Execute
      run: appcenter test run appium --app "mribelato-gmail.com/Alpha" --devices "mribelato-gmail.com/lista-s20" --token "af2d27c3a1ebc05b7f8d1ecfc1060116560e219a" --app-path src/test/resources/apks/calculadora.apk --test-series "master" --locale "en_US" --build-dir target/upload
   
